spring:
  main:
    allow-bean-definition-overriding: true
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_DEV_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_DEV_ROOT_USERNAME}
    password: ${DB_DEV_ROOT_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        time_zone: UTC
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQLDialect
  cache:
    type: jcache
    jcache:
      provider: com.hazelcast.cache.impl.HazelcastServerCachingProvider
      config: classpath:hazelcast.xml
spring-doc:
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
app:
  jwt-secret: ${JWT_SECRET}
  jwt-expiration-milliseconds: ${JWT_EXPIRATION_MILLIS}
bucket4j:
  enabled: true
  filters:
    - cache-name: tasksRateLimiter
      url: .*
      rate-limits:
        - bandwidths:
            - capacity: 10
              time: 30
              unit: minutes
              refill-speed: greedy