spring:
  datasource:
    url: jdbc:mysql://localhost:3306/taskmanager
    #    url: jdbc:mysql://root:o2PThfSoQgYMvBTDAjYM@containers-us-west-194.railway.app:6058/railway?useTimezone=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
  #    password: o2PThfSoQgYMvBTDAjYM
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        time_zone: UTC
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQLDialect
spring-doc:
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
app:
  jwt-secret: 781dcdf14b25e5191fe614744275d51b861c39d40cf8fcb4a6bebc310ca2a6f5
  jwt-expiration-milliseconds: 604800000
