spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    #    url: jdbc:mysql://localhost:3306/taskmanager
    url: jdbc:mysql://root:JSur7lZs2Z6lrtevTuSX@containers-us-west-145.railway.app:7369/railway?useTimezone=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: JSur7lZs2Z6lrtevTuSX
  #    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        time_zone: UTC
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQLDialect
  cache:
    type: jcache
    jcache:
      provider: com.hazelcast.cache.impl.HazelcastServerCachingProvider
      config: classpath:hazelcast.xml
spring-doc:
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
app:
  jwt-secret: 781dcdf14b25e5191fe614744275d51b861c39d40cf8fcb4a6bebc310ca2a6f5
  jwt-expiration-milliseconds: 604800000
bucket4j:
  enabled: true
  filters:
    - cache-name: tasksRateLimiter
      url: .*
      rate-limits:
        - bandwidths:
            - capacity: 200
              time: 30
              unit: minutes